### ISSUE TITLE
Explain "Testing with Local Dependencies" Better

### ISSUE THREAD

**Issue by JimLynchCodes** [webrtc-rs/webrtc#158]
The section in this README "Testing with Local Dependencies" is extremely confusing...

All it says is, "Follows this instruction about how to replace dependencies with patch for local testing: https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html"

The link has NOTHING to do with this project- it's just general cargo documentation...

What am I supposed to replace? What am I supposed to be replacing it with? WHAT the heck is the purpose of this in the first place??

Please expand this section of the README because currently it's incredibly confusing.

Thanks!

**Comment by k0nserv** [comment]
You'd do something like this

```toml
# Cargo.toml

[dependencies]
webrtc = "0.4"

[patch.crates-io]
webrtc = { path= "/path/to/local/checkout-of/webrtc" }
```

This way your local copy will replace `webrtc` from crates.io
