### ISSUE TITLE
Adjust rustfmt configuration

### ISSUE THREAD

**Issue by koushiro** [webrtc-rs/webrtc#397]
I want to make the following changes to the rustfmt configuration of the repo, I wonder if the maintainer can accept it?

```toml
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
```
